name: Run Terraform Plan and Raise PR

on:
    push:
      branches: [ "dev" ]

env:
  AWS_REGION: ap-south-2      

permissions:
  id-token: write 
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
            role-to-assume: arn:aws:iam::778477254970:role/tf_s3_state
            aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS Session
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Post Terraform Plan Comment in PR
        uses: towardsthecloud/terraform-plan-pr-commenter@v1
        with:
          planfile: tfplan.binary
          aws-region: ${{ env.AWS_REGION }}